name: casloginfix
version: '${version}'
main: fr.kumakuma215.casloginfix.CasLoginFix
api-version: 1.20
depend:
  - ProtocolLib
softdepend:
  - SkinsRestorer
commands:
  setskin:
    description: "Modify your skin"
    usage: /setskin <url|player> <string>
