package fr.eirb.caslogin.exceptions.api;

public enum Errors {
	BANNED_NOT_AN_USER,
	BANNER_NOT_AN_USER,
	EXPIRES_NOT_A_TIMESTAMP,
	USER_DOES_NOT_HAVE_ROLE,
	USER_HAS_ROLE,
	ROLE_NOT_IN_DATABASE,
	USER_NOT_IN_DATABASE,
	NOT_ENOUGH_KEYS,
	NO_AUTH_CODE_FOR_UUID,
	AUTH_CODE_EXPIRED,
	INVALID_AUTH_CODE,
	INVALID_TOKEN,
	USER_BANNED,
	USER_NOT_LOGGED_IN,
	USER_ALREADY_LOGGED_IN,
	COULD_NOT_GENERATE_CSRF
}
